[project]
name = "comiset"
version = "0.2"
description = "Meu Mestrado"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "jupyter>=1.1.1",
    "jupyterlab>=4.6.3",
    "duckdb>=1.5.5",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "polars>=1.44.1",
    "matplotlib>=3.11.1",
    "scikit-learn>=1.9.0",
    "pm4py>=2.7.23.8",
    "skpm>=0.1.0",
    "graphviz>=0.21",
]
